<?php
/**
 * User: Green
 * Date: 2013/9/2
 * Time: 上午 12:18
 */
$cs = Yii::app()->clientScript;
$cs->registerCSSFile(Yii::app()->request->baseUrl.'/css/staff.css');
?>
<div id="main">
	<div class="member"><div class="name">Queenie</div><div class="birthday">04/08</div><div>/聽音樂看電影/ </div><div>/有很多聲音需要安靜聆聽/ </div></div><div class="member"><div class="name">小樂 </div><div class="birthday">12/17 </div><div>"/談天、遊玩、電影、音樂、美食/ " </div><div>/讓松濤走進你/妳的心，與我們一同起舞吧！/ </div></div><div class="member"><div class="name">跳跳 </div><div class="birthday">11/19 </div><div>/電影、展覽、音樂、星星、遊樂/ </div><div>/跟著我們一起走吧，聽見你心中的聲音。/ </div></div><div class="member"><div class="name">方瑜 </div><div class="birthday">01/20 </div><div>/逛網拍~吃東西~畫圖/ </div><div>/歡迎加入松濤電台:)/ </div></div><div class="member"><div class="name">郝爾 </div><div class="birthday">09/16</div><div>/和煦　徐風　挾帶愜意的藏書　松濤滿座/ </div><div>/交替踩換輪軸踏板　承載　我們的先祖　和未來　層疊/ </div></div><div class="member"><div class="name">游力</div><div class="birthday">05/21 </div><div>/網頁設計與桌上遊戲/ </div><div>/ (手機鈴響....) /<br>/ 「喂? 是游力嗎? 電台又炸了...」 /</div></div><div class="member"><div class="name">莉莉</div><div class="birthday">12/10</div><div>/閱讀.聽音樂.唱歌/</div><div>/大家要支持松濤電台喔~~~快來跟我們一起玩嘛!!!/</div></div><div class="member"><div class="name">儒儒</div><div class="birthday">10/27</div><div>/音樂 閱讀 放空放空放空/</div><div>/哎唷!!!!!!!! 聽眾們別急著走唄 聽聽節目啊&gt;___________&lt;/</div></div><div class="member"><div class="name">羊羊</div><div class="birthday">06/10</div><div>/聽音樂.唱歌.看小說/</div><div>/歡迎大家收聽松濤電台~!!/</div></div><div class="member"><div class="name">峰哥</div><div class="birthday">09/24</div><div>/唱歌.看電影/</div><div>/恭請收聽中大人專屬的松濤電台!!/</div></div><div class="member"><div class="name">Hiking</div><div class="birthday">06/29</div><div>/音樂.設計.創意.APP/</div><div>/屬於中大人的松濤電台，看見，世界/</div></div><div class="member"><div class="name">大嘎</div><div class="birthday">05/12</div><div>/音樂,唱歌,亂寫東西,減肥>< /</div><div>/你可以 找到 另一種悸動 。發現 ，自己。/</div></div><div class="member"><div class="name">維克</div><div class="birthday">10/22</div><div>/感官娛樂/</div><div>/聽一次就上癮。/</div></div><div class="member"><div class="name">蛋蛋</div><div class="birthday">10/29</div><div>/認真熱血過生活/</div><div>/耶斯！聽音樂，蹦蹦跳＞＜！/</div></div><div class="member"><div class="name">阿嘎</div><div class="birthday">04/07</div><div>/一切與美有關的、認真享受人生。/</div><div>/希望，每一個你也可以在聆聽中發現快樂。/</div></div><div class="member"><div class="name">Fami</div><div class="birthday">09/19</div><div>/看電影.逛街.聽音樂/</div><div>/松濤給你最美好的夜晚喔~耶!!!/</div></div><div class="member"><div class="name">克利斯</div><div class="birthday">04/08</div><div>/宅/</div><div>/看電影聽音樂看漫畫動畫 人生最大的幸福是做自己想做的是哈哈~/</div></div><div class="member"><div class="name">白鳥</div><div class="birthday">09/25</div><div>/種花養魚 看書 大自然 畫畫/</div><div>/甚麼是有意義的人生? 這個世界若是因為你的存在而變得更好 那麼他就有意義了/</div></div><div class="member"><div class="name">呂ㄚ包</div><div class="birthday"></div><div>/動腦、發呆和睡覺/</div><div>/一起來譜出屬於自己的樂章吧~~~/</div></div><div class="member"><div class="name">沈ㄚ青</div><div class="birthday"></div><div>/音樂、電影和美食/</div><div>/歡迎你一起來享受人生吧!!!!!/</div></div><div class="member"><div class="name">蔡ㄚ玲</div><div class="birthday"></div><div>/拍照、散步和閒晃/</div><div>/與你一同踏出爛漫的步伐~~~/</div></div>		</div>